name: SnowMod
main: TheNote\SnowMod\SnowMod
version: 3.0.0
author: TheNote
api: 4.9.0
mcpe-protocol: 554
description: SnowMod by TheNote
commands:
  snowmod:
    description: "Enable/Disable the Snowmod"
    permission: snowmod.use
permissions:
  snowmod.use:
    description: "Enable/Disable the Snowmod"
    default: op

