name: SnowMod
main: TheNote\SnowMod\SnowMod
version: 3.0.2
author: TheNote
api: 4.12.1
mcpe-protocol: 560
description: SnowMod by TheNote
commands:
  snowmod:
    description: "Enable/Disable the Snowmod"
    permission: snowmod.use
permissions:
  snowmod.use:
    description: "Enable/Disable the Snowmod"
    default: op

