name: SnowMod
main: TheNote\SnowMod\SnowMod
version: 3.0.1
author: TheNote
api: 4.10.0
mcpe-protocol: 557
description: SnowMod by TheNote
commands:
  snowmod:
    description: "Enable/Disable the Snowmod"
    permission: snowmod.use
permissions:
  snowmod.use:
    description: "Enable/Disable the Snowmod"
    default: op

