name: SnowMod
main: TheNote\SnowMod\SnowMod
version: 2.0.1
author: TheNote
api: 3.16.0
mcpe-protocol: 422 #V.1.16.200
description: SnowMod by TheNote

commands:
  snowmod:
    description: "Enable/Disable the Snowmod"
    permission: "snowmod.use"
